### ISSUE TITLE
Error when Python 3.6 deepcopy copies context

### ISSUE THREAD

**Issue by uwefladrich** [uwefladrich/scriptengine#52]
The solution to #47 uses `copy.deepcopy` under the hood in a few places. However, this is a problem when Python version 3.6 is used (3.7, 3.8, 3.9 are tested and not affected).

In particular, `context["se"]["instance"]`, which holds a reference to the actual ScriptEngine instance, poses some kind of recursive reference when it is deepcopied in the `run()` method of the same SE instance. This leads in Python 3.6 to an error like

```
Traceback (most recent call last):

  [... part in ScriptEngine that calls copy.deepcopy(context)...]

  File "/usr/lib64/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)

  [...long traceback in the copy library...]

  File "/usr/lib64/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.RLock objects
```

**Comment by uwefladrich** [comment]
There are two kinds of `deepcopy` calls in SE at the moment: (i) Direct calls from the SE code and (ii) `deepcopy` call from `deepdiff.Delta.__add__`. Both cases must be avoided in Python 3.6
