### ISSUE TITLE
SE installation error

### ISSUE THREAD

**Issue by uwefladrich** [uwefladrich/scriptengine#58]
A fresh installation of ScriptEngine 0.12.3 from PyPI yields
```
se --version
Traceback (most recent call last):
  File "[...]/se/bin/se", line 7, in <module>
    from scriptengine.cli.se import main
  File "[...]/se/lib64/python3.6/site-packages/scriptengine/cli/se.py", line 37, in <module>
    from scriptengine.tasks.core.loader import load as load_tasks
  File "[...]/se/lib64/python3.6/site-packages/scriptengine/tasks/core/__init__.py", line 13, in <module>
    from .task import Task
  File "[...]/se/lib64/python3.6/site-packages/scriptengine/tasks/core/task.py", line 11, in <module>
    from scriptengine.yaml.noparse_strings import (
ModuleNotFoundError: No module named 'scriptengine.yaml'
```

**Comment by uwefladrich** [comment]
The issue is that `scriptengine/yaml` is not found by `setuptools.find_packages()` because it has no `__init__.py`. Thus, `scriptengine.yaml` is not packaged in the PyPI package.

The secondary issue is that the automatic testing always install from sources and therefore not catching the problem. Need to add a github action that installs from PyPI.
