### ISSUE TITLE
deepdiff problems with rrule objects

### ISSUE THREAD

**Issue by mandresm** [uwefladrich/scriptengine#64]
Description
-----------

When updating the `context` inside a `do`, with `deepdiff` version `6.2.1`, and there is a variable of type `rrule` previously defined in the `context`, scriptengine returns a traceback with error `TypeError: object of type 'rrule' has no len()`.

If the version of `deepdiff` is `5.7.0`, the error does not occur.

Script to reproduce the error
-----------------------------

```yaml
-
  base.context:
    schedule: !rrule >
      DTSTART:19900101
      RRULE:FREQ=YEARLY;UNTIL=20000101
-
  do:
    - base.context:
        foo: 2
```

Machines
----------
- Ollie (AWI)
- Juwels (JSC)

**Versions**
```
asttokens         2.0.8
backcall          0.2.0
decorator         5.1.1
deepdiff          6.2.1
deepmerge         1.0.1
executing         1.1.1
ipdb              0.13.9
ipython           8.5.0
jedi              0.18.1
Jinja2            3.1.2
MarkupSafe        2.1.1
matplotlib-inline 0.1.6
ordered-set       4.0.2
parso             0.8.3
pexpect           4.8.0
pickleshare       0.7.5
pip               21.1.3
prompt-toolkit    3.0.31
ptyprocess        0.7.0
pure-eval         0.2.2
Pygments          2.13.0
python-dateutil   2.8.1
PyYAML            6.0
scriptengine      0.12.5  /p/home/jusers/andres-martinez1/juwels/scriptengine
setuptools        56.0.0
six               1.16.0
stack-data        0.5.1
toml              0.10.2
traitlets         5.5.0
wcwidth           0.2.5
```

Work-around
-------------

```
pip install deepdiff==5.7.0
```
or changing the dependency version in `setup.py`.

#Traceback

```
Traceback (most recent call last):
  File "/p/home/jusers/andres-martinez1/juwels/.venvs/se/bin/se", line 33, in <module>
    sys.exit(load_entry_point('scriptengine', 'console_scripts', 'se')())
  File "/p/home/jusers/andres-martinez1/juwels/scriptengine/scriptengine/cli/se.py", line 167, in main
    context["se"]["instance"].run(script, context)
  File "/p/home/jusers/andres-martinez1/juwels/scriptengine/scriptengine/engines/simple_script_engine.py", line 69, in run
    context_update = self._guarded_run(todo, local_context)
  File "/p/home/jusers/andres-martinez1/juwels/scriptengine/scriptengine/engines/simple_script_engine.py", line 29, in _guarded_run
    return runner.run(context)
  File "/p/home/jusers/andres-martinez1/juwels/scriptengine/scriptengine/jobs.py", line 152, in run
    return ContextUpdate(context, local_context)
  File "/p/home/jusers/andres-martinez1/juwels/scriptengine/scriptengine/context.py", line 77, in __init__
    self.delta = context_delta(base, second)
  File "/p/home/jusers/andres-martinez1/juwels/scriptengine/scriptengine/context.py", line 39, in context_delta
    return Delta(DeepDiff(first, second))
  File "/p/home/jusers/andres-martinez1/juwels/.venvs/se/lib/python3.9/site-packages/deepdiff/diff.py", line 303, in __init__
    self._diff(root, parents_ids=frozenset({id(t1)}), _original_type=_original_type)
  File "/p/home/jusers/andres-martinez1/juwels/.venvs/se/lib/python3.9/site-packages/deepdiff/diff.py", line 1519, in _diff
    self._diff_dict(level, parents_ids, local_tree=local_tree)
  File "/p/home/jusers/andres-martinez1/juwels/.venvs/se/lib/python3.9/site-packages/deepdiff/diff.py", line 585, in _diff_dict
    self._diff(next_level, parents_ids_added, local_tree=local_tree)
  File "/p/home/jusers/andres-martinez1/juwels/.venvs/se/lib/python3.9/site-packages/deepdiff/diff.py", line 1531, in _diff
    self._diff_iterable(level, parents_ids, _original_type=_original_type, local_tree=local_tree)
  File "/p/home/jusers/andres-martinez1/juwels/.venvs/se/lib/python3.9/site-packages/deepdiff/diff.py", line 632, in _diff_iterable
    self._diff_iterable_in_order(level, parents_ids, _original_type=_original_type, local_tree=local_tree)
  File "/p/home/jusers/andres-martinez1/juwels/.venvs/se/lib/python3.9/site-packages/deepdiff/diff.py", line 732, in _diff_iterable_in_order
    self._diff_ordered_iterable_by_difflib(
  File "/p/home/jusers/andres-martinez1/juwels/.venvs/se/lib/python3.9/site-packages/deepdiff/diff.py", line 863, in _diff_ordered_iterable_by_difflib
    seq = difflib.SequenceMatcher(isjunk=None, a=level.t1, b=level.t2, autojunk=False)
  File "/p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/difflib.py", line 214, in __init__
    self.set_seqs(a, b)
  File "/p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/difflib.py", line 226, in set_seqs
    self.set_seq2(b)
  File "/p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/difflib.py", line 280, in set_seq2
    self.__chain_b()
  File "/p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/difflib.py", line 328, in __chain_b
    n = len(b)
TypeError: object of type 'rrule' has no len()
```

**Comment by uwefladrich** [comment]
Yes, I can confirm that `deepdiff 6.2.1` breaks the `base.context` task in the way shown above. It works with versions `5.7.0`, `5.8.0`, and `5.8.1`.

I can track it down to a single commit in the `deepdiff` repository, which introduces `difflib` to the code. That is, unfortunately, a bit more comprehensive change. I will try to reproduce the bug without ScriptEngine and report.

For now, I think the solution will be to limit the `deepdiff` version accordingly in the ScriptEngine dependencies.

Thanks for reporting!

**Comment by zklaus** [comment]
I think this issue should be reopened, since the pinning of the dependency is not a long term solution. It would be helpful to link the issue on the deepdiff repo. I will introduce the corresponding pin on the conda-forge package in conda-forge/scriptengine-feedstock#1.

**Comment by uwefladrich** [comment]
It is understood that pinning the `deepdiff` version is just a temporary workaround to make sure not to break things for SE users. I was able to come up with a short test case that does not include SE, so I can report upstream. Although it might be a problem even further down the call tree (in `libdiff`), I am not sure yet. It might take some time to find out and fix.

I don't know if the canonical way to handle this kind of problem is to keep this open until it is fixed upstream but I don't mind doing it.

**Comment by uwefladrich** [comment]
see seperman/deepdiff#355
